### ISSUE TITLE
java.lang.NullPointerException if StateLog is not enabled

### ISSUE THREAD

**Issue by kleash** [kptfh/left-join-on-timeout#1]
Hi,

I have tried using your library. This is how I built the Stream:

```
	public static void main(String[] args) {
		KStreamBuilder kStreamBuilder = new KStreamBuilder();

		KStream<String, String> sourceLhs = kStreamBuilder.stream(Serdes.String(), Serdes.String(),
				"LEFT-Q");
		KStream<String, String> sourceRhs = kStreamBuilder.stream(Serdes.String(), Serdes.String(),
				"RIGHT-Q");

		new LeftJoinOnTimeoutBuilder<>(kStreamBuilder, sourceLhs, sourceRhs,
				(lhs, rhs) -> StringUtils.isNotEmpty(rhs) ? "status=true " + lhs + "+" + rhs
						: "status=false " + lhs + "+",
				TimeUnit.SECONDS.toMillis(10), TimeUnit.SECONDS.toMillis(100))
						.sinkTo("FINAL-Q",
								producer(ByteArraySerializer.class, ByteArraySerializer.class))
						.serdes(Serdes.String(), Serdes.String(), Serdes.String(), Serdes.String())
						.buildTopology();

		KafkaStreams kafkaStreams = new KafkaStreams(kStreamBuilder, streamsConfig());
		kafkaStreams.cleanUp();
		kafkaStreams.start();

	}
```

I am receiving this exception if there is one message in LEFT queue:

```
Exception in thread "left_join_client_1-StreamThread-1" java.lang.NullPointerException
	at kafkastreams.leftjoin.ScheduleProcessor.process(ScheduleProcessor.java:25)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:45)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:131)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:82)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:198)
	at org.apache.kafka.streams.processor.internals.AssignedTasks$2.apply(AssignedTasks.java:347)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.applyToRunningTasks(AssignedTasks.java:420)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.process(AssignedTasks.java:339)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndPunctuate(StreamThread.java:648)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:513)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:482)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:459)

```

Somehow the scheduledStateStore is null in ScheduleProcessor if I am not calling enableStateLog in LeftJoinOnTimeoutBuilder

**Comment by kptfh** [comment]
fixed. Thanks.

**Comment by kleash** [comment]
Thank you. It's working fine now.

If you don't mind me asking, what exactly is the use of statelog? Is this similar to changelog-topic concept? Normally kafka-stream will automatically create change logic topic behind-the-scene, right?

**Comment by kptfh** [comment]
Yes, Kafka Streams will use it to restore our state store state.
